apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-order
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard